# Handling data in pandas

In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv('heart.csv')

In [2]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [4]:
#using specific columns
df=pd.read_csv("heart.csv",usecols=['Age','Sex','RestingBP','MaxHR'])

In [10]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,...,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,...,172,N,0.0,Up,0
1,49,F,NAP,160,180,...,156,N,1.0,Flat,1
2,37,M,ATA,130,283,...,98,N,0.0,Up,0
3,48,F,ASY,138,214,...,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,...,122,N,0.0,Up,0
5,39,M,NAP,120,339,...,170,N,0.0,Up,0
6,45,F,ATA,130,237,...,170,N,0.0,Up,0
7,54,M,ATA,110,208,...,142,N,0.0,Up,0
8,37,M,ASY,140,207,...,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,...,120,N,0.0,Up,0
10,37,F,NAP,130,211,...,142,N,0.0,Up,0
11,58,M,ATA,136,164,...,99,Y,2.0,Flat,1
12,39,M,ATA,120,204,...,145,N,0.0,Up,0
13,49,M,ASY,140,234,...,140,Y,1.0,Flat,1
14,42,F,NAP,115,211,...,137,N,0.0,Up,0
15,54,F,ATA,120,273,...,150,N,1.5,Flat,0
16,38,M,ASY,110,196,...,166,N,0.0,Flat,1
17,43,F,ATA,120,201,...,165,N,0.0,Up,0
18,60,M,ASY,100,248,...,125,N,1.0,Flat,1
19,36,M,ATA,120,267,...,160,N,3.0,Flat,1
20,43,F,TA,100,223,...,142,N,0.0,Up,0
21,44,M,ATA,120,184,...,142,N,1.0,Flat,0
22,49,F,ATA,124,201,...,164,N,0.0,Up,0
23,44,M,ATA,150,288,...,150,Y,3.0,Flat,1
24,40,M,NAP,130,215,...,138,N,0.0,Up,0
25,36,M,NAP,130,209,...,178,N,0.0,Up,0
26,53,M,ASY,124,260,...,112,Y,3.0,Flat,0
27,52,M,ATA,120,284,...,118,N,0.0,Up,0
28,53,F,ATA,113,468,...,127,N,0.0,Up,0
29,51,M,ATA,125,188,...,145,N,0.0,Up,0
30,53,M,NAP,145,518,...,130,N,0.0,Flat,1
31,56,M,NAP,130,167,...,114,N,0.0,Up,0
32,54,M,ASY,125,224,...,122,N,2.0,Flat,1
33,41,M,ASY,130,172,...,130,N,2.0,Flat,1
34,43,F,ATA,150,186,...,154,N,0.0,Up,0
35,32,M,ATA,125,254,...,155,N,0.0,Up,0
36,65,M,ASY,140,306,...,87,Y,1.5,Flat,1
37,41,F,ATA,110,250,...,142,N,0.0,Up,0
38,48,F,ATA,120,177,...,148,N,0.0,Up,0
39,48,F,ASY,150,227,...,130,Y,1.0,Flat,0
40,54,F,ATA,150,230,...,130,N,0.0,Up,0
41,54,F,NAP,130,294,...,100,Y,0.0,Flat,1
42,35,M,ATA,150,264,...,168,N,0.0,Up,0
43,52,M,NAP,140,259,...,170,N,0.0,Up,0
44,43,M,ASY,120,175,...,120,Y,1.0,Flat,1
45,59,M,NAP,130,318,...,120,Y,1.0,Flat,0
46,37,M,ASY,120,223,...,168,N,0.0,Up,0
47,50,M,ATA,140,216,...,170,N,0.0,Up,0
48,36,M,NAP,112,340,...,184,N,1.0,Flat,0
49,41,M,ASY,110,289,...,170,N,0.0,Flat,1

In [11]:
# skipping rows
df=pd.read_csv('heart.csv',nrows=10)

In [12]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
5,39,M,NAP,120,339,0,Normal,170,N,0.0,Up,0
6,45,F,ATA,130,237,0,Normal,170,N,0.0,Up,0
7,54,M,ATA,110,208,0,Normal,142,N,0.0,Up,0
8,37,M,ASY,140,207,0,Normal,130,Y,1.5,Flat,1
9,48,F,ATA,120,284,0,Normal,120,N,0.0,Up,0

In [13]:
#encoding in utl format
df=pd.read_csv('heart.csv',encoding='latin-1')

In [14]:
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

# changing data type

In [34]:

df=pd.read_csv('heart.csv',dtype={'Age':float})
df=pd.read_csv('heart.csv',dtype={"oldpeak":int})
df=pd.read_csv('heart.csv',dtype={'HeartDisease':int})
df=pd.read_csv('heart.csv',dtype={'oldpeak':object})
df=pd.read_csv('heart.csv',dtype={'HeartDisease':bool})
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    bool
dtypes: bool(1), float64(1), int64(5), object(5)
memory usage: 79.9+ KB

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,False
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,True
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,False
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,True
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,False
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,True
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,True
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,True
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,True
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,False

In [36]:
# Handling date format values
df2=pd.read_csv('/content/IPL Matches 2008-2020.csv')

In [37]:
df2

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [38]:
df2.info() #date column is in object format

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    object
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: float64(1), int64(2), object(14)
memory usage: 108.5+ KB

In [43]:
df2=pd.read_csv('/content/IPL Matches 2008-2020.csv',parse_dates=['date'])

In [41]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    object
 2   date             816 non-null    datetime64[ns]
 3   player_of_match  812 non-null    object
 4   venue            816 non-null    object
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    object
 7   team2            816 non-null    object
 8   toss_winner      816 non-null    object
 9   toss_decision    816 non-null    object
 10  winner           812 non-null    object
 11  result           812 non-null    object
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    object
 14  method           19 non-null     object
 15  umpire1          816 non-null    object
 16  umpire2          816 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(2), object(13)
memory usage: 108.5+ KB

In [47]:
#Chaanging names in data
df2=pd.read_csv('/content/IPL Matches 2008-2020.csv',usecols=['id','city','venue','team1','team2','winner','result'])
df2

,id,city,venue,team1,team2,winner,result
0,335982,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,runs
1,335983,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,runs
2,335984,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,wickets
3,335985,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,wickets
4,335986,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders,wickets
...,...,...,...,...,...,...,...
811,1216547,Dubai,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,tie
812,1237177,Dubai,Dubai International Cricket Stadium,Mumbai Indians,Delhi Capitals,Mumbai Indians,runs
813,1237178,Abu Dhabi,Sheikh Zayed Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,wickets
814,1237180,Abu Dhabi,Sheikh Zayed Stadium,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,runs
815,1237181,Dubai,Dubai International Cricket Stadium,Delhi Capitals,Mumbai Indians,Mumbai Indians,wickets

In [65]:
def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB"
    if name == "Delhi Daredevils" :
        return "DD"
    if name == "Delhi Daredevils" :
        return "DD"
    if name == "Kolkata Knight Riders":
        return "KKR"
    if name =="Mumbai Indians":
        return "MI"
    else:
        return name
rename("Royal Challengers Bangalore")

'RCB'

In [74]:
df3=pd.read_csv('IPL Matches 2008-2020.csv',converters={'team1':rename})

In [75]:
df3

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,DD,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,MI,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,KKR,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,MI,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

In [76]:
df3=pd.read_csv('IPL Matches 2008-2020.csv',converters={'team2':rename})
df3

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,Royal Challengers Bangalore,KKR,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,RCB,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,Royal Challengers Bangalore,MI,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,MI,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon